// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAC3NJ4ayxoWmvAqUY26EUBjVAqGsXUUP4',
    appId: '1:8427053870:web:fceb4e8a2478f2b17d90bf',
    messagingSenderId: '8427053870',
    projectId: 'noted-3640a',
    authDomain: 'noted-3640a.firebaseapp.com',
    storageBucket: 'noted-3640a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSH624pho4HyLPlyvRCcm8eOq12z9lagA',
    appId: '1:8427053870:android:db73c2c15a5bd8767d90bf',
    messagingSenderId: '8427053870',
    projectId: 'noted-3640a',
    storageBucket: 'noted-3640a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAf93RrcGNSga7kOpAJG5-4T_YJIvAXvzA',
    appId: '1:8427053870:ios:779b33fece6c8d4a7d90bf',
    messagingSenderId: '8427053870',
    projectId: 'noted-3640a',
    storageBucket: 'noted-3640a.firebasestorage.app',
    iosBundleId: 'com.example.noted',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAC3NJ4ayxoWmvAqUY26EUBjVAqGsXUUP4',
    appId: '1:8427053870:web:adf982ec00a1695a7d90bf',
    messagingSenderId: '8427053870',
    projectId: 'noted-3640a',
    authDomain: 'noted-3640a.firebaseapp.com',
    storageBucket: 'noted-3640a.firebasestorage.app',
  );
}
